typedef FP64 Method_DO( MO a );
typedef struct OwcpChild *Method_YO( MO a );
typedef MO (* Method_OoO)( MO &a, MO b );
typedef bool Method_BO( MO a );
typedef void Method_VOpS( MO a, void *b, ST c );
typedef bool (* Method_BOO)( MO a, MO b );
typedef void *Method_pO( MO a );
typedef FP32 Method_FO( MO a );
typedef SI64 Method_LO( MO a );
typedef void *(* Method_poO)( MO &a, MO b );
typedef void *Method_po( MO &a );
typedef FP80 Method_EO( MO a );
typedef struct MetilException *Method_XO( MO a );
typedef void (* Method_VoO)( MO &a, MO b );
typedef void Method_Vopp( MO &a, void *b, void *c );
typedef SI32 Method_IO( MO a );
typedef void Method_VoY( MO &a, struct OwcpChild *b );
typedef void *(* Method_poOM)( MO &a, MO b, const MachineId *c );
typedef MO Method_OO( MO a );
typedef MO (* Method_OOO)( MO a, MO b );
typedef void (* Method_VOO)( MO a, MO b );
typedef void Method_VoPS( MO &a, const void *b, ST c );
typedef void Method_Vo( MO &a );
typedef ST Method_SO( MO a );
typedef MO Method_OOS( MO a, ST b );
typedef const MachineId *Method_MO( MO a );
