#ifndef TYPECONSTRUCTOR_CONVERTTOGPUTEX_H
#define TYPECONSTRUCTOR_CONVERTTOGPUTEX_H

#include "TypeConstructor.h"

BEG_METIL_LEVEL1_NAMESPACE;

class TypeConstructor_ConvertToGpuTex : public TypeConstructor {
public:
};

END_METIL_LEVEL1_NAMESPACE;

#endif // TYPECONSTRUCTOR_CONVERTTOGPUTEX_H
