    if ( type == "Vo" ) { args = "ERNS0_2MOE"; }
    if ( type == "OO" ) { args = "ENS0_2MOE"; }
    if ( type == "BO" ) { args = "ENS0_2MOE"; }
    if ( type == "IO" ) { args = "ENS0_2MOE"; }
    if ( type == "LO" ) { args = "ENS0_2MOE"; }
    if ( type == "SO" ) { args = "ENS0_2MOE"; }
    if ( type == "FO" ) { args = "ENS0_2MOE"; }
    if ( type == "DO" ) { args = "ENS0_2MOE"; }
    if ( type == "EO" ) { args = "ENS0_2MOE"; }
    if ( type == "VOt" ) { args = "ENS0_2MOEERNS_6StringE"; }
    if ( type == "pO" ) { args = "ENS0_2MOE"; }
    if ( type == "Vot" ) { args = "ERNS0_2MOEERNS_6StringE"; }
    if ( type == "po" ) { args = "ERNS0_2MOE"; }
    if ( type == "VoPS" ) { args = "ERNS0_2MOEPKvx"; }
    if ( type == "VOpS" ) { args = "ENS0_2MOEPvx"; }
    if ( type == "OOO" ) { args = "ENS0_2MOEENS0_2MOE"; }
    if ( type == "BOO" ) { args = "ENS0_2MOEENS0_2MOE"; }
    if ( type == "VoO" ) { args = "ERNS0_2MOEENS0_2MOE"; }
    if ( type == "OoO" ) { args = "ERNS0_2MOEENS0_2MOE"; }
    if ( type == "OOS" ) { args = "ENS0_2MOEx"; }
    if ( type == "VoY" ) { args = "ERNS0_2MOEEPNS0_9OwcpChildE"; }
