typedef void Method_Vo( MO &a );
typedef MO Method_OO( MO a );
typedef bool Method_BO( MO a );
typedef SI32 Method_IO( MO a );
typedef SI64 Method_LO( MO a );
typedef ST Method_SO( MO a );
typedef FP32 Method_FO( MO a );
typedef FP64 Method_DO( MO a );
typedef FP80 Method_EO( MO a );
typedef void Method_VOt( MO a, String &b );
typedef void *Method_pO( MO a );
typedef void Method_Vot( MO &a, String &b );
typedef void *Method_po( MO &a );
typedef void Method_VoPS( MO &a, const void *b, ST c );
typedef void Method_VOpS( MO a, void *b, ST c );
typedef MO (* Method_OOO)( MO a, MO b );
typedef bool (* Method_BOO)( MO a, MO b );
typedef void (* Method_VoO)( MO &a, MO b );
typedef MO (* Method_OoO)( MO &a, MO b );
